---
name: Release

on:
  workflow_dispatch:
  schedule:
    - cron: 0 17 * * *

permissions:
  contents: write

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          if [[ $GITHUB_EVENT_NAME == workflow_dispatch ]]; then
            ./scripts/release.sh -f
          else
            ./scripts/release.sh
          fi
        env:
          GH_TOKEN: ${{ github.token }}
